app/gathering/forms.py
# Import Form
from flask_wtf import FlaskForm

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import StringField, DateField, SelectField, SubmitField \
                    , FileField, BooleanField

# Import Form validators
from wtforms.validators import DataRequired

# Define Sample form  (WTForms)
class SampleForm(FlaskForm):
    identification = StringField('Identification', validators=[DataRequired(message='This field is obligatory')])
    collected_date = DateField('Collected_date', format='%m/%d/%Y', validators=[DataRequired(message='This field is obligatory')])
    country = SelectField('Country', choices=[('Brazil', 'Brazil'), ('South Africa', 'South Africa')], validators=[DataRequired(message='This field is obligatory')] )
    city = StringField('City', validators=[DataRequired(message='This field is obligatory')])
    district = StringField('District', validators=[DataRequired(message='This field is obligatory')])
    number = StringField('Number', validators=[DataRequired(message='This field is obligatory')])
    submit = SubmitField('Save')

# Define Slide form  (WTForms)
class SlideForm(FlaskForm):
    creation_date = DateField('Creation_Date', format='%m/%d/%Y')
    technique = StringField('Technique', validators=[DataRequired(message='This field is obligatory')])
    images  = BooleanField('Images')
    submit = SubmitField('Save')

# Define Image form  (WTForms)
class ImageForm(FlaskForm):
    filename = StringField('Filename')
    cdate = DateField('CDate', format='%m/%d/%Y')
    zoom = StringField('Zoom')
    image_url = StringField('Image_url')
    submit = SubmitField('Save')

app/gathering/__init__.py
# Import Flask Blueprint to set gathering blueprint
from flask import Blueprint

# Define the blueprint: 'gathering', set its url prefix: app.url/gathering
gathering = Blueprint('gathering', __name__, url_prefix='/gathering', template_folder='../templates/gathering')

from . import views

app/gathering/views.py
# Import flask dependencies
from flask import request, render_template, flash, redirect, url_for

# Import flask login dependencies
from flask_login import current_user, login_required

# Import Gathering blueprint configuration
from . import gathering

# Import app configurations
from .. import db

# Import module forms
from .forms import SampleForm, SlideForm, ImageForm

# Import module models (i.e. Sample)
from ..models import  Sample, Slide, Image

# Set the route and accepted methods

@gathering.route('/')
@login_required
def dashboard():
    user = current_user
    samples = Sample.query.count()
    slides = Slide.query.count()
    images = Image.query.count()
    return render_template('index.html', title='ParasiteWatch Dashboard', \
                           user=user, samples = samples, slides = slides, \
                           images = images)

@gathering.route('/samples', methods=['GET'])
@login_required
def samples():
    user = current_user
    form = SampleForm()
    samples = Sample.query.all()
    return render_template('sample/sample_index.html', title='ParasiteWatch Dashboard', user=user, form=form, samples=samples)

@gathering.route('/samples/new', methods=['GET', 'POST'])
@login_required
def samples_new():
    user = current_user
    form = SampleForm()
    slides = Slide.query.filter_by(sample_id=None)
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_slides = request.form.getlist('slides')
            slide_objects = []
            for slide_id in selected_slides:
                slide_objects.append(Slide.query.filter_by(id=slide_id).first())
            sample = Sample(collected_date = form.collected_date.data, identification = form.identification.data,\
                            country = form.country.data, city = form.city.data, \
                            district = form.district.data, number = form.district.data, \
                            slides = slide_objects)
            db.session.add(sample)
            db.session.commit()
            db.session.flush()
            flash('Sample created successfully', category = 'success')
            return redirect(url_for('gathering.samples'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.samples_new'))
    if request.method == 'GET':
        return render_template('sample/sample_new.html', title = 'ParasiteWatch Slides', user = user, form = form, slides = slides)


@gathering.route('/samples/destroy/<sample_id>', methods=['POST'])
@login_required
def samples_destroy(sample_id):
    user = current_user
    form = SampleForm()
    if request.method == 'POST':
        sample = Sample.query.filter_by(id = sample_id).first()
        db.session.delete(sample)
        db.session.commit()
        db.session.flush()
        flash('Sample deleted successfully', category='success')
        return redirect(url_for('gathering.samples'))
    else:
        return render_template('index.html', title='ParasiteWatch Dashboard', \
                               user = user, form = form)

@gathering.route('/samples/edit/<sample_id>', methods=['GET', 'POST'])
@login_required
def samples_edit(sample_id):
    user = current_user
    form = SampleForm()
    sample = Sample.query.filter_by(id=sample_id).first()
    slides = Slide.query.filter((Slide.sample_id==None) | (Slide.sample_id==sample.id))
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_slides = request.form.getlist('slides')
            slide_objects = []
            for slide_id in selected_slides:
                slide_objects.append(Slide.query.filter_by(id=slide_id).first())
            sample.collected_date = form.collected_date.data
            sample.identification = form.identification.data
            sample.country = form.country.data
            sample.city = form.city.data
            sample.district = form.district.data
            sample.number = form.district.data
            sample.slides = slide_objects
            db.session.commit()
            db.session.flush()
            flash('Sample edited successfully', category = 'success')
            return redirect(url_for('gathering.samples'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.samples_edit'))
    if request.method == 'GET':
        return render_template('sample/sample_edit.html', title = 'ParasiteWatch Slides', user = user, form = form, sample = sample, slides = slides)

@gathering.route('/sample/<sample_id>/gallery', methods=['GET'])
@login_required
def samples_gallery(sample_id):
    user = current_user
    sample = Sample.query.filter_by(id=slide_id).first()
    if request.method == 'GET':
        return render_template('sample/sample_gallery.html', title = 'ParasiteWatch Slides', user = user, sample = sample)


@gathering.route('/slides', methods=['GET'])
@login_required
def slides():
    user = current_user
    form = SlideForm()
    slides = Slide.query.all()
    return render_template('slide/slide_index.html', title='ParasiteWatch Samples', user=user, slides=slides, form=form)

@gathering.route('/slides/new', methods=['GET', 'POST'])
@login_required
def slides_new():
    user = current_user
    form = SlideForm()
    images = Image.query.filter_by(slide_id=None)
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_images = request.form.getlist('images')
            image_objects = []
            for image_id in selected_images:
                image_objects.append(Image.query.filter_by(id=image_id).first())
            slide = Slide(creation_date = form.creation_date.data, technique = form.technique.data, images = image_objects)
            db.session.add(slide)
            db.session.commit()
            db.session.flush()
            flash('Slide created successfully', category = 'success')
            return redirect(url_for('gathering.slides'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.slides_new'))
    if request.method == 'GET':
        return render_template('slide/slide_new.html', title = 'ParasiteWatch \
                               Slides', user = user, images = images \
                               ,form = form)


@gathering.route('/slides/destroy/<slide_id>', methods=['POST'])
@login_required
def slides_destroy(slide_id):
    user = current_user
    form = SlideForm()
    if request.method == 'POST':
        slide  = Slide.query.filter_by(id=slide_id).first()
        db.session.delete(slide)
        db.session.commit()
        db.session.flush()
        flash('Slide deleted successfully', category='success')
        return redirect(url_for('gathering.slides'))
    else:
        return render_template('slide/slide_index.html', title='ParasiteWatch Dashboard', user = user, form = form)


@gathering.route('/slides/edit/<slide_id>', methods=['GET', 'POST'])
@login_required
def slides_edit(slide_id):
    user = current_user
    form = SlideForm()
    slide = Slide.query.filter_by(id=slide_id).first()
    images = Image.query.filter((Image.slide_id==None) | (Image.slide_id==slide.id))
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_images = request.form.getlist('images')
            image_objects = []
            for image_id in selected_images:
                image_objects.append(Image.query.filter_by(id=image_id).first())
            slide.creation_date = form.creation_date.data
            slide.technique = form.technique.data
            slide.images = image_objects
            db.session.commit()
            db.session.flush()
            flash('Slide updated successfully', category = 'success')
            return redirect(url_for('gathering.slides'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.slides_new'))
    if request.method == 'GET':
        return render_template('slide/slide_edit.html', title = 'ParasiteWatch Slides', user = user, form = form, slide = slide, images = images)

@gathering.route('/slides/<slide_id>/gallery', methods=['GET'])
@login_required
def slides_gallery(slide_id):
    user = current_user
    slide = Slide.query.filter_by(id=slide_id).first()
    if request.method == 'GET':
        return render_template('slide/slide_gallery.html', title = 'ParasiteWatch Slides', user = user, slide = slide)


@gathering.route('/images', methods=['GET'])
@login_required
def images():
    user = current_user
    images = Image.query.all()
    form = ImageForm()
    return render_template('image/image_index.html', title='ParasiteWatch Images', user=user, images=images, form=form)

@gathering.route('/images/new', methods=['GET', 'POST'])
@login_required
def images_new():
    form = ImageForm()
    user = current_user
    if request.method == 'POST':
        if form.validate_on_submit():
            image = Image(capture_date=form.cdate.data, zoom=form.zoom.data, filename=form.filename.data, url=form.image_url.data)
            db.session.add(image)
            db.session.commit()
            db.session.flush()
            flash('Image created successfully.', category='success')
            return redirect(url_for('gathering.images'))
        flash('Error sending form data.', category='danger')
        return redirect(url_for('gathering.images_new'))
    if request.method == 'GET':
        return render_template('image/image_new.html', title='ParasiteWatch New Image', user=user, form=form)

@gathering.route('/images/edit/<image_id>', methods=['GET', 'POST'])
@login_required
def images_edit(image_id):
    form = ImageForm()
    user = current_user
    image  = Image.query.filter_by(id=image_id).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            image.capture_date = form.cdate.data
            image.zoom = form.zoom.data

app/templates/gathering/image/image_edit.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css') }}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/jquery-bar-rating/dist/themes/css-stars.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/uppy/dist/uppy.min.css') }}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='gathering/css/style.css') }}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='gathering/images/favicon.png') }}" />
  </head>
  <body>
    <!-- partial:partials/_settings-panel.html -->
    {% include 'partials/_settings-panel.html' %}
    <!-- partial -->
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      {% with user=user %}
      {% include 'partials/_navbar.html' %}
      {% endwith %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <div class="row row-offcanvas row-offcanvas-right">
          <!-- partial:partials/_sidebar.html -->
          {% include 'partials/_sidebar.html' %}
          <!-- partial -->
          <div class="content-wrapper">
            <!-- partial:partials/_flash.html -->
            {% include 'partials/_flash.html' %}
            <!-- partial -->
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Edit Image</h4>
                <form class='form-sample' id='form-sample' role="form" enctype="multipart/form-data" method="POST" action="{{ url_for('gathering.images_edit', image_id = image.id) }}">
                  {{ form.hidden_tag() }}
                  {{ form.csrf_token }}
                  <div class="form-group">
                    <label>Name</label>
                    <input type="text" class="form-control p_input" name="filename" id="filename" value='{{ image.filename }}'>
                  </div>
                  <div class="form-group">
                    <label>Date</label>
                    <div id="datepicker-popup" class="input-group date">
                      <input type="text" class="form-control p_input" name="cdate" id="cdate" value="{{ image.capture_date.strftime('%m/%d/%Y') }}">
                      <div class="input-group-addon">
                        <span class="mdi mdi-calendar"></span>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Zoom</label>
                    <input type="text" class="form-control p_input" name="zoom" id="zoom" value='{{ image.zoom }}'>
                  </div>
                  <div class="form-group">
                    <label>Image</label>
                    <input type='hidden' class='form-control p_input' name='image_url' id='image_url'>
                    <button class="uppymodalopenerbtn" style="display: none;">Open Uppy Dashboard Modal</button>
                    <div class="dashboardcontainer" id='uppy-dashboard'></div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          {% include 'partials/_footer.html' %}
          <!-- partial -->
        </div>
        <!-- row-offcanvas ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/uppy/dist/uppy.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{{ url_for('static', filename='gathering/js/off-canvas.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/misc.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/settings.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/hoverable-collapse.js') }}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{{ url_for('static', filename='gathering/js/uppy.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/formpickers.js') }}"></script>
    <!-- End custom js for this page-->
  </body>

</html>

app/templates/gathering/image/image_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css') }}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/jquery-bar-rating/dist/themes/css-stars.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" />
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='gathering/css/style.css') }}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='gathering/images/favicon.png') }}" />
  </head>
  <body>
    <!-- partial:partials/_settings-panel.html -->
    {% include 'partials/_settings-panel.html' %}
    <!-- partial -->
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      {% with user=user %}
      {% include 'partials/_navbar.html' %}
      {% endwith %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <div class="row row-offcanvas row-offcanvas-right">
          <!-- partial:partials/_sidebar.html -->
          {% include 'partials/_sidebar.html' %}
          <!-- partial -->
          <div class="content-wrapper">
            <!-- partial:partials/_flash.html -->
            {% include 'partials/_flash.html' %}
            <!-- partial -->
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">List of Images</h4>
                <div class="table-sorter-wrapper">
                  <table id="order-listing" class="table table-hover" style="width:100%">
                    <thead>
                      <th>Collected Date</th>
                      <th>Zoom</th>
                      <th>Image Name</th>
                      <th>Image</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </thead>
                    <tbody>
                      {% for image in images %}
                      <tr>
                        <td>{{ image.capture_date.strftime('%d/%m/%Y')  }}</td>
                        <td>{{ image.zoom }}</td>
                        <td>{{ image.filename }}</td>
                        <td>
                          <img src="{{ image.url }}" style="width:180px;height:180px;">
                        </td>
                        <td>
                          <form method="GET" action="{{url_for('gathering.images_edit', image_id=image.id)}}">
                            {{ form.hidden_tag() }}
                            {{ form.csrf_token }}
                            <button type='submit' class="btn btn-outline-primary">Edit</button>
                          </form>
                        </td>
                        <td>
                          <form method="POST" action="{{url_for('gathering.images_destroy', image_id=image.id)}}">
                            {{ form.hidden_tag() }}
                            {{ form.csrf_token }}
                            <button type='submit' class="btn btn-outline-danger">Delete</button>
                          </form>
                        </td>
                      </tr>
                      {%  endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          {% include 'partials/_footer.html' %}
          <!-- partial -->
        </div>
        <!-- row-offcanvas ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/datatables.net/js/jquery.dataTables.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js') }}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="{{ url_for('static', filename='node_modules/chart.js/dist/Chart.min.js') }}"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="{{ url_for('static', filename='gathering/js/off-canvas.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/misc.js') }}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{{ url_for('static', filename='gathering/js/data-table.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/settings.js') }}"></script>
    <!-- End custom js for this page-->
  </body>

</html>

app/templates/gathering/image/image_new.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css') }}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/jquery-bar-rating/dist/themes/css-stars.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/uppy/dist/uppy.min.css') }}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='gathering/css/style.css') }}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='gathering/images/favicon.png') }}" />
  </head>
  <body>
    <!-- partial:partials/_settings-panel.html -->
    {% include 'partials/_settings-panel.html' %}
    <!-- partial -->
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      {% with user=user %}
      {% include 'partials/_navbar.html' %}
      {% endwith %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <div class="row row-offcanvas row-offcanvas-right">
          <!-- partial:partials/_sidebar.html -->
          {% include 'partials/_sidebar.html' %}
          <!-- partial -->
          <div class="content-wrapper">
            <!-- partial:partials/_flash.html -->
            {% include 'partials/_flash.html' %}
            <!-- partial -->
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">New Image</h4>
                <form class='form-sample' id='form-sample' role="form" enctype="multipart/form-data" method="POST" action="{{ url_for('gathering.images_new') }}">
                  {{ form.hidden_tag() }}
                  {{ form.csrf_token }}
                  <div class="form-group">
                    <label>Name</label>
                    <input type="text" class="form-control p_input" name="filename" id="filename">
                  </div>
                  <div class="form-group">
                    <label>Date</label>
                    <div id="datepicker-popup" class="input-group date">
                      <input type="text" class="form-control p_input" name="cdate" id="cdate">
                      <div class="input-group-addon">
                        <span class="mdi mdi-calendar"></span>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Zoom</label>
                    <input type="text" class="form-control p_input" name="zoom" id="zoom">
                  </div>
                  <div class="form-group">
                    <label>Image</label>
                    <input type='hidden' class='form-control p_input' name='image_url' id='image_url'>
                    <button class="uppymodalopenerbtn" style="display: none;">Open Uppy Dashboard Modal</button>
                    <div class="dashboardcontainer" id='uppy-dashboard'></div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          {% include 'partials/_footer.html' %}
          <!-- partial -->
        </div>
        <!-- row-offcanvas ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/uppy/dist/uppy.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{{ url_for('static', filename='gathering/js/off-canvas.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/misc.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/settings.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/hoverable-collapse.js') }}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{{ url_for('static', filename='gathering/js/uppy.js') }}"></script>
    <script src="{{ url_for('static', filename='gathering/js/formpickers.js') }}"></script>
    <!-- End custom js for this page-->
  </body>

</html>