app/gathering/forms.py
# Import Form
from flask_wtf import FlaskForm

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import StringField, DateField, SelectField, SubmitField \
                    , FileField, BooleanField

# Import Form validators
from wtforms.validators import DataRequired

# Define Sample form  (WTForms)
class SampleForm(FlaskForm):
    identification = StringField('Identification', validators=[DataRequired(message='This field is obligatory')])
    collected_date = DateField('Collected_date', format='%m/%d/%Y', validators=[DataRequired(message='This field is obligatory')])
    country = SelectField('Country', choices=[('Brazil', 'Brazil'), ('South Africa', 'South Africa')], validators=[DataRequired(message='This field is obligatory')] )
    city = StringField('City', validators=[DataRequired(message='This field is obligatory')])
    district = StringField('District', validators=[DataRequired(message='This field is obligatory')])
    number = StringField('Number', validators=[DataRequired(message='This field is obligatory')])
    submit = SubmitField('Save')

# Define Slide form  (WTForms)
class SlideForm(FlaskForm):
    creation_date = DateField('Creation_Date', format='%m/%d/%Y')
    technique = StringField('Technique', validators=[DataRequired(message='This field is obligatory')])
    images  = BooleanField('Images')
    submit = SubmitField('Save')

# Define Image form  (WTForms)
class ImageForm(FlaskForm):
    filename = StringField('Filename')
    cdate = DateField('CDate', format='%m/%d/%Y')
    zoom = StringField('Zoom')
    image_url = StringField('Image_url')
    submit = SubmitField('Save')

app/gathering/__init__.py
# Import Flask Blueprint to set gathering blueprint
from flask import Blueprint

# Define the blueprint: 'gathering', set its url prefix: app.url/gathering
gathering = Blueprint('gathering', __name__, url_prefix='/gathering', template_folder='../templates/gathering')

from . import views

app/gathering/views.py
# Import flask dependencies
from flask import request, render_template, flash, redirect, url_for

# Import flask login dependencies
from flask_login import current_user, login_required

# Import Gathering blueprint configuration
from . import gathering

# Import app configurations
from .. import db

# Import module forms
from .forms import SampleForm, SlideForm, ImageForm

# Import module models (i.e. Sample)
from ..models import  Sample, Slide, Image

# Set the route and accepted methods

@gathering.route('/')
@login_required
def dashboard():
    user = current_user
    samples = Sample.query.count()
    slides = Slide.query.count()
    images = Image.query.count()
    return render_template('index.html', title='ParasiteWatch Dashboard', \
                           user=user, samples = samples, slides = slides, \
                           images = images)

@gathering.route('/samples', methods=['GET'])
@login_required
def samples():
    user = current_user
    form = SampleForm()
    samples = Sample.query.all()
    return render_template('sample/sample_index.html', title='ParasiteWatch Dashboard', user=user, form=form, samples=samples)

@gathering.route('/samples/new', methods=['GET', 'POST'])
@login_required
def samples_new():
    user = current_user
    form = SampleForm()
    slides = Slide.query.filter_by(sample_id=None)
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_slides = request.form.getlist('slides')
            slide_objects = []
            for slide_id in selected_slides:
                slide_objects.append(Slide.query.filter_by(id=slide_id).first())
            sample = Sample(collected_date = form.collected_date.data, identification = form.identification.data,\
                            country = form.country.data, city = form.city.data, \
                            district = form.district.data, number = form.district.data, \
                            slides = slide_objects)
            db.session.add(sample)
            db.session.commit()
            db.session.flush()
            flash('Sample created successfully', category = 'success')
            return redirect(url_for('gathering.samples'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.samples_new'))
    if request.method == 'GET':
        return render_template('sample/sample_new.html', title = 'ParasiteWatch Slides', user = user, form = form, slides = slides)


@gathering.route('/samples/destroy/<sample_id>', methods=['POST'])
@login_required
def samples_destroy(sample_id):
    user = current_user
    form = SampleForm()
    if request.method == 'POST':
        sample = Sample.query.filter_by(id = sample_id).first()
        db.session.delete(sample)
        db.session.commit()
        db.session.flush()
        flash('Sample deleted successfully', category='success')
        return redirect(url_for('gathering.samples'))
    else:
        return render_template('index.html', title='ParasiteWatch Dashboard', \
                               user = user, form = form)

@gathering.route('/samples/edit/<sample_id>', methods=['GET', 'POST'])
@login_required
def samples_edit(sample_id):
    user = current_user
    form = SampleForm()
    sample = Sample.query.filter_by(id=sample_id).first()
    slides = Slide.query.filter((Slide.sample_id==None) | (Slide.sample_id==sample.id))
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_slides = request.form.getlist('slides')
            slide_objects = []
            for slide_id in selected_slides:
                slide_objects.append(Slide.query.filter_by(id=slide_id).first())
            sample.collected_date = form.collected_date.data
            sample.identification = form.identification.data
            sample.country = form.country.data
            sample.city = form.city.data
            sample.district = form.district.data
            sample.number = form.district.data
            sample.slides = slide_objects
            db.session.commit()
            db.session.flush()
            flash('Sample edited successfully', category = 'success')
            return redirect(url_for('gathering.samples'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.samples_edit'))
    if request.method == 'GET':
        return render_template('sample/sample_edit.html', title = 'ParasiteWatch Slides', user = user, form = form, sample = sample, slides = slides)

@gathering.route('/sample/<sample_id>/gallery', methods=['GET'])
@login_required
def samples_gallery(sample_id):
    user = current_user
    sample = Sample.query.filter_by(id=slide_id).first()
    if request.method == 'GET':
        return render_template('sample/sample_gallery.html', title = 'ParasiteWatch Slides', user = user, sample = sample)


@gathering.route('/slides', methods=['GET'])
@login_required
def slides():
    user = current_user
    form = SlideForm()
    slides = Slide.query.all()
    return render_template('slide/slide_index.html', title='ParasiteWatch Samples', user=user, slides=slides, form=form)

@gathering.route('/slides/new', methods=['GET', 'POST'])
@login_required
def slides_new():
    user = current_user
    form = SlideForm()
    images = Image.query.filter_by(slide_id=None)
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_images = request.form.getlist('images')
            image_objects = []
            for image_id in selected_images:
                image_objects.append(Image.query.filter_by(id=image_id).first())
            slide = Slide(creation_date = form.creation_date.data, technique = form.technique.data, images = image_objects)
            db.session.add(slide)
            db.session.commit()
            db.session.flush()
            flash('Slide created successfully', category = 'success')
            return redirect(url_for('gathering.slides'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.slides_new'))
    if request.method == 'GET':
        return render_template('slide/slide_new.html', title = 'ParasiteWatch \
                               Slides', user = user, images = images \
                               ,form = form)


@gathering.route('/slides/destroy/<slide_id>', methods=['POST'])
@login_required
def slides_destroy(slide_id):
    user = current_user
    form = SlideForm()
    if request.method == 'POST':
        slide  = Slide.query.filter_by(id=slide_id).first()
        db.session.delete(slide)
        db.session.commit()
        db.session.flush()
        flash('Slide deleted successfully', category='success')
        return redirect(url_for('gathering.slides'))
    else:
        return render_template('slide/slide_index.html', title='ParasiteWatch Dashboard', user = user, form = form)


@gathering.route('/slides/edit/<slide_id>', methods=['GET', 'POST'])
@login_required
def slides_edit(slide_id):
    user = current_user
    form = SlideForm()
    slide = Slide.query.filter_by(id=slide_id).first()
    images = Image.query.filter((Image.slide_id==None) | (Image.slide_id==slide.id))
    if request.method == 'POST':
        if form.validate_on_submit():
            selected_images = request.form.getlist('images')
            image_objects = []
            for image_id in selected_images:
                image_objects.append(Image.query.filter_by(id=image_id).first())
            slide.creation_date = form.creation_date.data
            slide.technique = form.technique.data
            slide.images = image_objects
            db.session.commit()
            db.session.flush()
            flash('Slide updated successfully', category = 'success')
            return redirect(url_for('gathering.slides'))
        flash('Error sending form data', category = 'danger')
        return redirect(url_for('gathering.slides_new'))
    if request.method == 'GET':
        return render_template('slide/slide_edit.html', title = 'ParasiteWatch Slides', user = user, form = form, slide = slide, images = images)

@gathering.route('/slides/<slide_id>/gallery', methods=['GET'])
@login_required
def slides_gallery(slide_id):
    user = current_user
    slide = Slide.query.filter_by(id=slide_id).first()
    if request.method == 'GET':
        return render_template('slide/slide_gallery.html', title = 'ParasiteWatch Slides', user = user, slide = slide)


@gathering.route('/images', methods=['GET'])
@login_required
def images():
    user = current_user
    images = Image.query.all()
    form = ImageForm()
    return render_template('image/image_index.html', title='ParasiteWatch Images', user=user, images=images, form=form)

@gathering.route('/images/new', methods=['GET', 'POST'])
@login_required
def images_new():
    form = ImageForm()
    user = current_user
    if request.method == 'POST':
        if form.validate_on_submit():
            image = Image(capture_date=form.cdate.data, zoom=form.zoom.data, filename=form.filename.data, url=form.image_url.data)
            db.session.add(image)
            db.session.commit()
            db.session.flush()
            flash('Image created successfully.', category='success')
            return redirect(url_for('gathering.images'))
        flash('Error sending form data.', category='danger')
        return redirect(url_for('gathering.images_new'))
    if request.method == 'GET':
        return render_template('image/image_new.html', title='ParasiteWatch New Image', user=user, form=form)

@gathering.route('/images/edit/<image_id>', methods=['GET', 'POST'])
@login_required
def images_edit(image_id):
    form = ImageForm()
    user = current_user
    image  = Image.query.filter_by(id=image_id).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            image.capture_date = form.cdate.data
            image.zoom = form.zoom.data

app/templates/gathering/partials/_flash.html
<div class="row">
  <div class="col-12">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-fill-{{ category }}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
  </div>
</div>

app/templates/gathering/partials/_footer.html
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
  </div>
</footer>

app/templates/gathering/partials/_navbar.html
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="{{ url_for('gathering.dashboard') }}">
      <img src="{{ url_for('static', filename='gathering/images/logo.svg') }}" alt="logo"/>
    </a>
    <a class="navbar-brand brand-logo-mini" href="{{ url_for('gathering.dashboard') }}">
      <img src="{{ url_for('static', filename='gathering/images/logo-mini.svg') }}" alt="logo"/>
    </a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <div class="search-field ml-4 d-none d-md-block">
      <form class="d-flex align-items-stretch h-100" action="#">
        <div class="input-group">
          <input type="text" class="form-control bg-transparent border-0" placeholder="Search">
          <div class="input-group-btn"><button type="button" class="btn bg-transparent dropdown-toggle px-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="mdi mdi-earth"></i>
              </button><div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="#">Today</a>
              <a class="dropdown-item" href="#">This week</a>
              <a class="dropdown-item" href="#">This month</a>
              <div role="separator" class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Month and older</a>
            </div>
          </div>
          <div class="input-group-addon bg-transparent border-0 search-button"><button type="submit" class="btn btn-sm bg-transparent px-0">
              <i class="mdi mdi-magnify"></i>
            </button>
          </div>
        </div>
      </form>
      </div><ul class="navbar-nav navbar-nav-right">
      <li class="nav-item d-none d-lg-block full-screen-link"><a class="nav-link">
          <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
        </a>
      </li>
      <li class="nav-item dropdown"><a class="nav-link dropdown-toggle nav-profile" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
          <span class="d-none d-lg-inline">{{ user.username }}</span>
          </a><div class="dropdown-menu navbar-dropdown w-100" aria-labelledby="profileDropdown">
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ url_for('auth.signout') }}"><i class="mdi mdi-logout mr-2 text-primary"></i>Signout
          </a>
        </div>
      </li>
      <li class="nav-item nav-logout d-none d-lg-block"><a class="nav-link" href="{{ url_for('auth.signout') }}">
          <i class="mdi mdi-power"></i>
        </a>
      </li>
      </ul><button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas"><span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

app/templates/gathering/partials/_settings-panel.html
<div id="settings-trigger"><i class="mdi mdi-settings"></i></div>
<div id="right-sidebar" class="settings-panel">
</div>
<div id="theme-settings" class="settings-panel">
  <i class="settings-close mdi mdi-close"></i>
  <p class="settings-heading">SIDEBAR SKINS</p>
  <div class="sidebar-bg-options selected" id="sidebar-default-theme"><div class="img-ss rounded-circle bg-gradient-primary border mr-3"></div>Default</div>
  <div class="sidebar-bg-options" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
  <p class="settings-heading mt-2">HEADER SKINS</p>
  <div class="color-tiles mx-0 px-4">
    <div class="tiles primary"></div>
    <div class="tiles success"></div>
    <div class="tiles warning"></div>
    <div class="tiles danger"></div>
    <div class="tiles pink"></div>
    <div class="tiles info"></div>
    <div class="tiles dark"></div>
    <div class="tiles light"></div>
  </div>
</div>

app/templates/gathering/partials/_sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('gathering.dashboard') }}">
        <span class="menu-title">Dashboard</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#samples" aria-expanded="false" aria-controls="samples">
        <span class="menu-title">Samples</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-file-tree menu-icon"></i>
      </a>
      <div class="collapse" id="samples">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('gathering.samples') }}">All Samples</a></li>
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('gathering.samples_new') }}">New Sample</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#slides" aria-expanded="false" aria-controls="slides">
        <span class="menu-title">Slides</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-microscope menu-icon"></i>
      </a>
      <div class="collapse" id="slides">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('gathering.slides') }}">All Slides</a></li>
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('gathering.slides_new') }}">New Slide</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#images" aria-expanded="false" aria-controls="images">
        <span class="menu-title">Images</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-folder-image menu-icon"></i>
      </a>
      <div class="collapse" id="images">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('gathering.images') }}">All Images</a></li>
          <li class="nav-item"> <a class="nav-link" href="{{ url_for('gathering.images_new') }}">New Image</a></li>
        </ul>
      </div>
    </li>
  </ul>
</nav>